# Generated by Django 3.1.4 on 2021-05-11 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя категории')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('text', models.TextField(verbose_name='Текст')),
                ('text1', models.TextField(blank=True, verbose_name='Текст1')),
                ('text2', models.TextField(blank=True, verbose_name='Текст2')),
                ('text3', models.TextField(blank=True, verbose_name='Текст3')),
                ('image', models.ImageField(blank=None, null=True, upload_to='images/', verbose_name='Изображение')),
                ('image2', models.ImageField(blank=True, upload_to='images/', verbose_name='Изображение 2')),
                ('in_archive', models.BooleanField(default=False)),
                ('blog_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.blogcategory', verbose_name='Имя категории')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
            },
        ),
    ]
