# Generated by Django 3.2.9 on 2021-11-21 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя категории')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('email', models.EmailField(blank=True, max_length=120, null=True, verbose_name='email')),
                ('description', models.CharField(blank=True, max_length=120, null=True, verbose_name='описание')),
            ],
            options={
                'verbose_name': 'Форма обратной связи',
                'verbose_name_plural': 'Формы обратной связи',
            },
        ),
        migrations.CreateModel(
            name='Formback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Полное наименование организации')),
                ('description', models.CharField(blank=True, max_length=120, null=True, verbose_name='Направление деятельности')),
                ('email', models.EmailField(blank=True, max_length=120, null=True, verbose_name='Email')),
                ('phone', models.CharField(max_length=11, verbose_name='Номер телефона')),
                ('iin', models.CharField(blank=True, max_length=120, null=True, verbose_name='БИН/ИИН')),
                ('adres', models.CharField(blank=True, max_length=120, null=True, verbose_name='Юридический адрес')),
                ('child', models.CharField(blank=True, max_length=120, null=True, verbose_name='Почтовый индекс')),
                ('bank', models.CharField(blank=True, max_length=120, null=True, verbose_name='Банковские реквизиты')),
                ('fio', models.CharField(blank=True, max_length=120, null=True, verbose_name='ФИО Первого руководителя')),
                ('first', models.CharField(blank=True, max_length=120, null=True, verbose_name='Должность первого руководителя')),
            ],
            options={
                'verbose_name': 'Юр лицо',
                'verbose_name_plural': 'Юр лица',
            },
        ),
        migrations.CreateModel(
            name='TopBack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(blank=True, max_length=120, null=True, verbose_name='Message')),
            ],
            options={
                'verbose_name': 'Форма обратной связи',
                'verbose_name_plural': 'Формы обратной связи',
            },
        ),
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('text', models.TextField(verbose_name='Текст')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение')),
                ('price', models.CharField(blank=True, max_length=10, null=True, verbose_name='Цена')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата')),
                ('in_archive', models.BooleanField(default=False)),
                ('blog_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.blogcategory', verbose_name='Имя категории')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
            },
        ),
    ]
