# Generated by Django 3.1.4 on 2021-05-11 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='ФИО')),
                ('description', models.CharField(blank=True, max_length=120, null=True, verbose_name='описание')),
                ('email', models.EmailField(blank=True, max_length=120, null=True, verbose_name='email')),
                ('phone', models.CharField(max_length=11, verbose_name='Телефон')),
                ('iin', models.CharField(blank=True, max_length=120, null=True, verbose_name='иин')),
                ('adres', models.CharField(blank=True, max_length=120, null=True, verbose_name='Адрес')),
                ('child', models.CharField(blank=True, max_length=120, null=True, verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Юр лицо',
                'verbose_name_plural': 'Юр лица',
            },
        ),
        migrations.CreateModel(
            name='TopBack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='ФИО')),
                ('description', models.CharField(blank=True, max_length=120, null=True, verbose_name='описание')),
                ('email', models.EmailField(blank=True, max_length=120, null=True, verbose_name='email')),
                ('phone', models.CharField(max_length=11, verbose_name='Телефон')),
                ('iin', models.CharField(blank=True, max_length=120, null=True, verbose_name='иин')),
                ('adres', models.CharField(blank=True, max_length=120, null=True, verbose_name='Адрес')),
                ('child', models.CharField(blank=True, max_length=120, null=True, verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Физ лицо',
                'verbose_name_plural': 'Физ лица',
            },
        ),
    ]
