# Generated by Django 3.2.9 on 2021-11-24 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211124_1037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topback',
            name='articles',
        ),
    ]
